<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>com.fs</groupId>
    <artifactId>starsector-gwt</artifactId>
    <version>0.97a-RC11</version>
    <packaging>jar</packaging>
    
    <properties>
        <gwt.version>2.12.2</gwt.version>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    
    <dependencies>
        <!-- GWT -->
        <dependency>
            <groupId>org.gwtproject</groupId>
            <artifactId>gwt-user</artifactId>
            <version>${gwt.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.gwtproject</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>${gwt.version}</version>
            <scope>provided</scope>
        </dependency>
        
        <!-- Elemental 2 -->
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-core</artifactId>
            <version>1.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-core</artifactId>
            <version>1.2.1</version>
            <classifier>sources</classifier>
        </dependency>
        
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-dom</artifactId>
            <version>1.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-dom</artifactId>
            <version>1.2.1</version>
            <classifier>sources</classifier>
        </dependency>
        
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-webgl</artifactId>
            <version>1.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.elemental2</groupId>
            <artifactId>elemental2-webgl</artifactId>
            <version>1.2.1</version>
            <classifier>sources</classifier>
        </dependency>

        <dependency>
            <groupId>com.google.jsinterop</groupId>
            <artifactId>jsinterop-annotations</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.google.jsinterop</groupId>
            <artifactId>jsinterop-annotations</artifactId>
            <version>2.0.2</version>
            <classifier>sources</classifier>
        </dependency>
        
        <dependency>
            <groupId>com.google.jsinterop</groupId>
            <artifactId>base</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.jsinterop</groupId>
            <artifactId>base</artifactId>
            <version>1.0.1</version>
            <classifier>sources</classifier>
        </dependency>

        <!-- JAXB (Required for Java 11+) -->
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.1</version>
        </dependency>
        
        <!-- Local Jars -->
        <dependency>
            <groupId>com.fs</groupId>
            <artifactId>fs-common</artifactId>
            <version>0.97a</version>
        </dependency>
        <dependency>
            <groupId>com.fs</groupId>
            <artifactId>starfarer-obf</artifactId>
            <version>0.97a</version>
        </dependency>
        <dependency>
            <groupId>com.fs</groupId>
            <artifactId>starfarer-api</artifactId>
            <version>0.97a</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <version>2.9.3</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-util</artifactId>
            <version>2.9.3</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20090211</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.9</version>
        </dependency>
        <dependency>
            <groupId>com.fs</groupId>
            <artifactId>fs-sound</artifactId>
            <version>0.97a</version>
        </dependency>
        <dependency>
            <groupId>com.thoughtworks.xstream</groupId>
            <artifactId>xstream</artifactId>
            <version>1.4.10</version>
        </dependency>
    </dependencies>
    
    <repositories>
        <repository>
            <id>google-sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/google-snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                    <excludes>
                        <exclude>com/fs/emul/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
                <configuration>
                    <webResources>
                        <resource>
                            <directory>libs</directory>
                            <targetPath>libs</targetPath>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>2.10.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <module>com.fs.Starfarer</module>
                    <generateJsInteropExports>true</generateJsInteropExports>
                    <strict>true</strict>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>