import java.io.*;import java.nio.file.*;import java.util.*;import java.util.jar.*;import org.objectweb.asm.*;
/** Diagnostic-only discovery timing for WeaponSpecLoader projectile/weapon methods. */
public final class PatchWeaponDiscoveryDiagnostics {
 static final String ENTRY="com/fs/starfarer/loading/WeaponSpecLoader.class",H="com/fs/starfarer/loading/BrowserWeaponDiscoveryDiag",LOADING="com/fs/starfarer/loading/LoadingUtils";
 public static void main(String[]x)throws Exception{if(x.length!=2)throw new IllegalArgumentException("usage: PatchWeaponDiscoveryDiagnostics input.jar output.jar");C c=new C();try(JarFile j=new JarFile(x[0]);JarOutputStream o=new JarOutputStream(Files.newOutputStream(Path.of(x[1])))){Enumeration<JarEntry>es=j.entries();while(es.hasMoreElements()){JarEntry e=es.nextElement(),n=new JarEntry(e.getName());n.setTime(e.getTime());o.putNextEntry(n);byte[]b;try(InputStream in=j.getInputStream(e)){b=read(in);}if(ENTRY.equals(e.getName())){c.classes++;b=patch(b,c);}o.write(b);o.closeEntry();}}if(c.classes!=1||c.methods!=2||c.begin!=2||c.dstart!=4||c.dend!=4||c.finish!=2)throw new IllegalStateException("weapon diag mismatch classes="+c.classes+" methods="+c.methods+" begin="+c.begin+" dstart="+c.dstart+" dend="+c.dend+" finish="+c.finish);System.out.println("Patched weapon discovery diagnostics methods=2 discoveryCalls=4");}
 static byte[]patch(byte[]b,C c){int ex=count(b);if(ex==12){c.methods=2;c.begin=2;c.dstart=4;c.dend=4;c.finish=2;return b;}if(ex!=0)throw new IllegalStateException("partial weapon diag calls="+ex);ClassReader r=new ClassReader(b);ClassWriter w=new ClassWriter(r,ClassWriter.COMPUTE_MAXS);r.accept(new ClassVisitor(Opcodes.ASM9,w){public MethodVisitor visitMethod(int a,String n,String d,String s,String[]e){MethodVisitor m=super.visitMethod(a,n,d,s,e);if((a&Opcodes.ACC_STATIC)==0||!"()V".equals(d))return m;return new MethodVisitor(Opcodes.ASM9,m){int kind;void h(String name){super.visitIntInsn(Opcodes.BIPUSH,kind);super.visitMethodInsn(Opcodes.INVOKESTATIC,H,name,"(I)V",false);}public void visitLdcInsn(Object v){if(kind==0&&v instanceof String){if("data/weapons/proj".equals(v)){kind=1;c.methods++;h("begin");c.begin++;}else if("data/weapons".equals(v)){kind=2;c.methods++;h("begin");c.begin++;}}super.visitLdcInsn(v);}public void visitMethodInsn(int op,String o,String n,String d,boolean i){if(kind!=0&&op==Opcodes.INVOKESTATIC&&LOADING.equals(o)&&"(Ljava/lang/String;Ljava/lang/String;)Ljava/util/List;".equals(d)){h("discoveryStart");c.dstart++;super.visitMethodInsn(op,o,n,d,i);h("discoveryEnd");c.dend++;return;}super.visitMethodInsn(op,o,n,d,i);}public void visitInsn(int op){if(kind!=0&&op==Opcodes.RETURN){h("finish");c.finish++;}super.visitInsn(op);}};}},0);return w.toByteArray();}
 static int count(byte[]b){int[]n={0};new ClassReader(b).accept(new ClassVisitor(Opcodes.ASM9){public MethodVisitor visitMethod(int a,String m,String d,String s,String[]e){return new MethodVisitor(Opcodes.ASM9){public void visitMethodInsn(int op,String o,String m,String d,boolean i){if(op==Opcodes.INVOKESTATIC&&H.equals(o))n[0]++;}};}},ClassReader.SKIP_DEBUG|ClassReader.SKIP_FRAMES);return n[0];}
 static byte[]read(InputStream i)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[65536];int n;while((n=i.read(b))>=0)o.write(b,0,n);return o.toByteArray();}static final class C{int classes,methods,begin,dstart,dend,finish;}
}
