import java.io.*; import java.nio.file.*; import java.util.*; import java.util.jar.*; import org.objectweb.asm.*;
public final class PatchRuleCommandDiagnostics {
  static final String AE="com/fs/starfarer/campaign/rules/A.class",RE="com/fs/starfarer/campaign/rules/Rules.class",H="com/fs/starfarer/campaign/rules/BrowserRuleCommandDiag";
  public static void main(String[]x)throws Exception{if(x.length!=2)throw new IllegalArgumentException("usage: PatchRuleCommandDiagnostics input.jar output.jar"); C c=new C(); try(JarFile j=new JarFile(x[0]);JarOutputStream o=new JarOutputStream(Files.newOutputStream(Path.of(x[1])))){Enumeration<JarEntry>es=j.entries();while(es.hasMoreElements()){JarEntry e=es.nextElement(),n=new JarEntry(e.getName());n.setTime(e.getTime());o.putNextEntry(n);byte[]b;try(InputStream in=j.getInputStream(e)){b=read(in);}if(AE.equals(e.getName())){c.ac++;b=patchA(b,c);}else if(RE.equals(e.getName())){c.rc++;b=patchR(b,c);}o.write(b);o.closeEntry();}} req(c);System.out.println("Patched rule command diagnostics start=1 end=2 attempt=1 rules=2");}
  static byte[] patchA(byte[]b,C c){int ex=count(b,"lookupStart")+count(b,"lookupEnd")+count(b,"classAttempt");if(ex==4){c.am=1;c.start=1;c.end=2;c.attempt=1;return b;}if(ex!=0)throw new IllegalStateException("partial command diag="+ex);ClassReader r=new ClassReader(b);ClassWriter w=new ClassWriter(r,ClassWriter.COMPUTE_MAXS);r.accept(new ClassVisitor(Opcodes.ASM9,w){public MethodVisitor visitMethod(int a,String n,String d,String s,String[]e){MethodVisitor m=super.visitMethod(a,n,d,s,e);if(!"getCommandClass".equals(n)||!"(Ljava/lang/String;)Ljava/lang/String;".equals(d))return m;c.am++;return new MethodVisitor(Opcodes.ASM9,m){public void visitCode(){super.visitCode();super.visitMethodInsn(Opcodes.INVOKESTATIC,H,"lookupStart","()V",false);c.start++;}public void visitMethodInsn(int op,String ow,String n,String d,boolean i){if(op==Opcodes.INVOKESTATIC&&"java/lang/Class".equals(ow)&&"forName".equals(n)){super.visitMethodInsn(Opcodes.INVOKESTATIC,H,"classAttempt","()V",false);c.attempt++;}super.visitMethodInsn(op,ow,n,d,i);}public void visitInsn(int op){if(op==Opcodes.ARETURN){super.visitMethodInsn(Opcodes.INVOKESTATIC,H,"lookupEnd","()V",false);c.end++;}super.visitInsn(op);}};}},0);return w.toByteArray();}
  static byte[] patchR(byte[]b,C c){int ex=count(b,"beginRules")+count(b,"finishRules");if(ex==2){c.rm=1;c.begin=1;c.finish=1;return b;}if(ex!=0)throw new IllegalStateException("partial Rules command diag="+ex);ClassReader r=new ClassReader(b);ClassWriter w=new ClassWriter(r,ClassWriter.COMPUTE_MAXS);r.accept(new ClassVisitor(Opcodes.ASM9,w){public MethodVisitor visitMethod(int a,String n,String d,String s,String[]e){MethodVisitor m=super.visitMethod(a,n,d,s,e);if(!"super".equals(n)||!"(Lcom/fs/starfarer/loading/ResourceLoaderState;)V".equals(d))return m;c.rm++;return new MethodVisitor(Opcodes.ASM9,m){public void visitCode(){super.visitCode();super.visitMethodInsn(Opcodes.INVOKESTATIC,H,"beginRules","()V",false);c.begin++;}public void visitInsn(int op){if(op==Opcodes.RETURN){super.visitMethodInsn(Opcodes.INVOKESTATIC,H,"finishRules","()V",false);c.finish++;}super.visitInsn(op);}};}},0);return w.toByteArray();}
  static int count(byte[]b,String name){int[]c={0};new ClassReader(b).accept(new ClassVisitor(Opcodes.ASM9){public MethodVisitor visitMethod(int a,String n,String d,String s,String[]e){return new MethodVisitor(Opcodes.ASM9){public void visitMethodInsn(int op,String o,String n,String d,boolean i){if(op==Opcodes.INVOKESTATIC&&H.equals(o)&&name.equals(n))c[0]++;}};}},ClassReader.SKIP_DEBUG|ClassReader.SKIP_FRAMES);return c[0];}
  static void req(C c){if(c.ac!=1||c.rc!=1||c.am!=1||c.rm!=1||c.start!=1||c.end!=2||c.attempt!=1||c.begin!=1||c.finish!=1)throw new IllegalStateException("mismatch ac="+c.ac+" rc="+c.rc+" am="+c.am+" rm="+c.rm+" start="+c.start+" end="+c.end+" attempt="+c.attempt+" begin="+c.begin+" finish="+c.finish);}
  static byte[] read(InputStream i)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[65536];int n;while((n=i.read(b))>=0)o.write(b,0,n);return o.toByteArray();} static final class C{int ac,rc,am,rm,start,end,attempt,begin,finish;}
}
