import java.io.*;import java.nio.file.*;import java.util.*;import java.util.jar.*;import org.objectweb.asm.*;
/** Diagnostic-only aggregate residual profiler for SpecStore.oO0000(). */
public final class PatchVariantResidualDiagnostics {
 static final String ENTRY="com/fs/starfarer/loading/SpecStore.class",METHOD="oO0000",DESC="()V",H="com/fs/starfarer/loading/BrowserVariantResidualDiag";
 static final String STORE="com/fs/starfarer/loading/new", SETTINGS="com/fs/starfarer/settings/StarfarerSettings", HULLS="com/fs/starfarer/loading/M", LOGGER="org/apache/log4j/Logger";
 public static void main(String[]x)throws Exception{if(x.length!=2)throw new IllegalArgumentException("usage: PatchVariantResidualDiagnostics input.jar output.jar");C c=new C();try(JarFile j=new JarFile(x[0]);JarOutputStream o=new JarOutputStream(Files.newOutputStream(Path.of(x[1])))){Enumeration<JarEntry>es=j.entries();while(es.hasMoreElements()){JarEntry e=es.nextElement(),n=new JarEntry(e.getName());n.setTime(e.getTime());o.putNextEntry(n);byte[]b;try(InputStream in=j.getInputStream(e)){b=read(in);}if(ENTRY.equals(e.getName())){c.classes++;b=patch(b,c);}o.write(b);o.closeEntry();}}req(c);System.out.println("Patched variant residual diagnostics loadLog=1 skipLog=1 duplicate=1 settings=1 hull=1 relationship=1");}
 static byte[] patch(byte[]b,C c){int ex=count(b);if(ex==12){c.methods=1;c.begin=c.loadLog=c.skipLog=c.duplicate=c.settings=c.hull=c.relationship=1;c.helper=12;return b;}if(ex!=0)throw new IllegalStateException("partial residual diag helperCalls="+ex);ClassReader r=new ClassReader(b);ClassWriter w=new ClassWriter(r,ClassWriter.COMPUTE_MAXS);r.accept(new ClassVisitor(Opcodes.ASM9,w){public MethodVisitor visitMethod(int a,String n,String d,String s,String[]e){MethodVisitor m=super.visitMethod(a,n,d,s,e);if(!METHOD.equals(n)||!DESC.equals(d))return m;c.methods++;return new MethodVisitor(Opcodes.ASM9,m){boolean loadLog,skipLog;void h(String n){super.visitMethodInsn(Opcodes.INVOKESTATIC,H,n,"()V",false);c.helper++;}public void visitCode(){super.visitCode();h("begin");c.begin++;}public void visitLdcInsn(Object v){if("Loading variant [".equals(v)){h("loadLogStart");loadLog=true;c.loadLog++;}else if("Skipping variant [".equals(v)){h("skipLogStart");skipLog=true;c.skipLog++;}super.visitLdcInsn(v);}public void visitMethodInsn(int op,String ow,String n,String d,boolean i){if(op==Opcodes.INVOKEVIRTUAL&&LOGGER.equals(ow)&&"info".equals(n)&&"(Ljava/lang/Object;)V".equals(d)&&(loadLog||skipLog)){super.visitMethodInsn(op,ow,n,d,i);if(loadLog){h("loadLogEnd");loadLog=false;}else{h("skipLogEnd");skipLog=false;}return;}if(op==Opcodes.INVOKESTATIC&&STORE.equals(ow)&&"(Ljava/lang/String;)Z".equals(d)){h("duplicateStart");super.visitMethodInsn(op,ow,n,d,i);h("duplicateEnd");c.duplicate++;return;}if(op==Opcodes.INVOKESTATIC&&SETTINGS.equals(ow)&&"()Z".equals(d)){h("settingsStart");super.visitMethodInsn(op,ow,n,d,i);h("settingsEnd");c.settings++;return;}if(op==Opcodes.INVOKESTATIC&&HULLS.equals(ow)&&"(Ljava/lang/String;)Z".equals(d)){h("hullStart");super.visitMethodInsn(op,ow,n,d,i);h("hullEnd");c.hull++;return;}if(op==Opcodes.INVOKESTATIC&&STORE.equals(ow)&&"()Ljava/util/List;".equals(d)){h("finish");c.relationship++;}super.visitMethodInsn(op,ow,n,d,i);}};}},0);return w.toByteArray();}
 static int count(byte[]b){int[]n={0};new ClassReader(b).accept(new ClassVisitor(Opcodes.ASM9){public MethodVisitor visitMethod(int a,String m,String d,String s,String[]e){if(!METHOD.equals(m)||!DESC.equals(d))return null;return new MethodVisitor(Opcodes.ASM9){public void visitMethodInsn(int op,String o,String n,String d,boolean i){if(op==Opcodes.INVOKESTATIC&&H.equals(o))n0();}void n0(){n[0]++;}};}},ClassReader.SKIP_DEBUG|ClassReader.SKIP_FRAMES);return n[0];}
 static void req(C c){if(c.classes!=1||c.methods!=1||c.begin!=1||c.loadLog!=1||c.skipLog!=1||c.duplicate!=1||c.settings!=1||c.hull!=1||c.relationship!=1||c.helper!=12)throw new IllegalStateException("residual diag mismatch classes="+c.classes+" methods="+c.methods+" begin="+c.begin+" loadLog="+c.loadLog+" skipLog="+c.skipLog+" duplicate="+c.duplicate+" settings="+c.settings+" hull="+c.hull+" relationship="+c.relationship+" helper="+c.helper);}
 static byte[]read(InputStream i)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[65536];int n;while((n=i.read(b))>=0)o.write(b,0,n);return o.toByteArray();}static final class C{int classes,methods,begin,loadLog,skipLog,duplicate,settings,hull,relationship,helper;}
}
