import com.fs.starfarer.BrowserDeferredTextureQueue;

public final class VerifyDeferredTexturePolicy {
    private VerifyDeferredTexturePolicy() {}
    private static void expect(String path, boolean expected) {
        boolean actual = BrowserDeferredTextureQueue.shouldDeferPath(path);
        if (actual != expected) throw new AssertionError(path + " actual=" + actual + " expected=" + expected);
    }
    public static void main(String[] args) {
        expect("graphics/illustrations/urban02.jpg", true);
        expect("graphics\\portraits\\godiva.jpg", true);
        expect("/graphics/portraits/portrait14.png", true);
        expect("graphics/hullmods/automated_repair_unit.png", true);
        expect("graphics/icons/markets/commodity_exports.png", true);
        expect("graphics/icons/cargo/supplies.png", true);
        expect("graphics/icons/intel/generic_intel.png", true);
        expect("graphics/icons/skills/elite_combat.png", true);
        expect("graphics/icons/missions/bounty.png", true);
        expect("graphics/icons/hullsys/fortress_shield.png", true);
        expect("graphics/icons/industry/heavyindustry.png", true);
        expect("graphics/icons/codex/ship.png", true);
        expect("graphics/icons/reports/report.png", true);
        expect("graphics/factions/hegemony.png", true);
        expect("graphics/planets/terran.jpg", true);
        expect("graphics/stations/station_mining00.png", true);
        expect("graphics/warroom/escort.png", true);
        expect("graphics/weapons/energy/beamfringe.png", false);
        expect("graphics/damage/damage1.png", true);
        expect("graphics/icons/tactical/assault.png", true);
        expect("graphics/debris/debris1.png", true);
        expect("graphics/missiles/harpoon/harpoon.png", true);
        expect("graphics/asteroids/asteroid1.png", true);
        expect("data/missions/forlornhope/icon.jpg", true);
        expect("graphics/ui/bgs/panel01_top_left.png", false);
        expect("graphics/hud/player_status_bg2.png", false);
        expect("graphics/ships/hound/hound_base.png", false);
        expect("graphics/ui/icons/damagetype_kinetic.png", false);
        expect("graphics/ui/icons/fleettab/LR_doodad_bg.png", true);
        expect("graphics/ui/icons/fleettab/buy.png", true);
        expect("graphics/ui/icons/fleettab/cargo_24x16.png", false);
        expect("graphics/ui/icons/fleettab/cargo_24x16b.png", true);
        expect("graphics/ui/icons/fleettab/chassis14x.png", true);
        expect("graphics/ui/icons/fleettab/cr16x.png", true);
        expect("graphics/ui/icons/fleettab/cr24x.png", false);
        expect("graphics/ui/icons/fleettab/cr24x16.png", true);
        expect("graphics/ui/icons/fleettab/cr32x.png", true);
        expect("graphics/ui/icons/fleettab/credits_24x24.png", false);
        expect("graphics/ui/icons/fleettab/crew_24x.png", false);
        expect("graphics/ui/icons/fleettab/fuel_24x16.png", false);
        expect("graphics/ui/icons/fleettab/hull16x.png", true);
        expect("graphics/ui/icons/fleettab/hull24x.png", false);
        expect("graphics/ui/icons/fleettab/hull32x.png", true);
        expect("graphics/ui/icons/fleettab/logistics_80x18.png", true);
        expect("graphics/ui/icons/fleettab/logistics_priority.png", true);
        expect("graphics/ui/icons/fleettab/logistics_priority2.png", true);
        expect("graphics/ui/icons/fleettab/logistics_priority_1box.png", true);
        expect("graphics/ui/icons/fleettab/logistics_priority_2box.png", true);
        expect("graphics/ui/icons/fleettab/logistics_priority_3box.png", true);
        expect("graphics/ui/icons/fleettab/logistics_priority_low.png", true);
        expect("graphics/ui/icons/fleettab/marines_24x24.png", false);
        expect("graphics/ui/icons/fleettab/more_info.png", true);
        expect("graphics/ui/icons/fleettab/mothball.png", true);
        expect("graphics/ui/icons/fleettab/personnel_24x16.png", false);
        expect("graphics/ui/icons/fleettab/rank0_16x24.png", true);
        expect("graphics/ui/icons/fleettab/rank1_16x24.png", true);
        expect("graphics/ui/icons/fleettab/rank2_16x24.png", true);
        expect("graphics/ui/icons/fleettab/rank3_16x24.png", true);
        expect("graphics/ui/icons/fleettab/refit.png", true);
        expect("graphics/ui/icons/fleettab/repair_rate_24x16.png", true);
        expect("graphics/ui/icons/fleettab/repair_rate_24x24.png", false);
        expect("graphics/ui/icons/fleettab/scuttle.png", true);
        expect("graphics/ui/icons/fleettab/sell.png", true);
        expect("graphics/ui/icons/fleettab/ship_store.png", true);
        expect("graphics/ui/icons/fleettab/ship_take.png", true);
        expect("graphics/ui/icons/fleettab/supplies16x.png", true);
        expect("graphics/ui/icons/fleettab/supplies_24x16.png", true);
        expect("graphics/ui/icons/fleettab/supplies_24x24.png", false);
        expect("graphics/ui/icons/fleettab/suspend_repairs.png", true);
        expect("graphics/ui/icons/fleettab/mod_or_future_asset.png", false);
        expect("graphics/ui/buttons/codex_arrow_up_category.png", true);
        expect("graphics/ui/buttons/toggleA20x_on.png", true);
        expect("graphics/ui/campaign_abilities.png", false);
        expect("graphics/ui/tripad_top_left_decor.png", false);
        expect("graphics/fx/slipstream_layer1.png", false);
        expect("graphics/backgrounds/hyperspace_bg_cool.jpg", false);
        expect("graphics/terrain/deep_hyperspace2.png", false);
        expect("graphics/icons/campaign/burn.png", false);
        expect("graphics/icons/abilities/emergency_burn.png", false);
        expect("graphics/hud/player_status_bg2.png", false);
        expect("graphics/ships/lasher/lasher_base.png", false);
        expect("graphics/fonts/orbitron20aa.fnt", false);
        System.out.println("VerifyDeferredTexturePolicy: OK");
    }
}
